### PR TITLE
Api web

### PR DESCRIPTION
**Pull request by eojohn**
Added external stylesheet + fonts +  integrated auth0 with custom social buttons.

### CODE REVIEW

**Comment by bholagabbar** [comment]
@eojohn Hey, could you [squash your commits](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/)? 

'git reset --soft HEAD~7`
`git add -A`
'git commit -m"Added login"`
`git push -f origin api-web`

**Review by bholagabbar — DISMISSED** [review]
Squash commits

**Comment by eojohn** [comment]
@bholagabbar  Will do that now

**Comment by bholagabbar** [comment]
@eojohn I think you forgot to rebase on the latest master branch. There are a bunch of conflicts which show modded java files and stuff. 

If you don't want to work with this branch anymore, just take the changes you made, make a new branch off the latest master, put your changes there, push it in one commit and then issue a PR

**Comment by bholagabbar** [comment]
@eojohn Could you do the above? You can close this PR and `ust take the changes you made, make a new branch off the latest master, put your changes there, push it in one commit and then issue a PR`

**Pull request closed without merging**
